### ISSUE TITLE
Resource 'corpora/stopwords' not found

### ISSUE THREAD

**Issue by ghost** [9seconds/rymtracks#15] opened 2014-02-11 03:48 UTC
Hello,
## RYMTracks-0.1.3

I have this problem :

$ rymtracks -h
Traceback (most recent call last):
  File "/usr/bin/rymtracks", line 9, in <module>
    load_entry_point('RYMTracks==0.1.3', 'console_scripts', 'rymtracks')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2029, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib64/python2.7/site-packages/rymtracks/**init**.py", line 51, in <module>
    from .core import execute
  File "/usr/lib64/python2.7/site-packages/rymtracks/core.py", line 8, in <module>
    from .services import Service
  File "/usr/lib64/python2.7/site-packages/rymtracks/services/**init**.py", line 10, in <module>
    from ..capitalization import capitalize
  File "/usr/lib64/python2.7/site-packages/rymtracks/capitalization/**init**.py", line 36, in <module>
    from .py2 import capitalize as specific_capitalize
  File "/usr/lib64/python2.7/site-packages/rymtracks/capitalization/py2.py", line 28, in <module>
    for _language in stopwords.fileids():
  File "/usr/lib64/python2.7/site-packages/nltk/corpus/util.py", line 68, in __getattr__
    self.__load()
  File "/usr/lib64/python2.7/site-packages/nltk/corpus/util.py", line 56, in __load
    except LookupError: raise e
LookupError: 

---

  Resource 'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/dslackw/.rymtracks/nltk'
    - '/home/dslackw/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'

---

**Comment by 9seconds** [comment] 2014-02-11 19:57
Thanks for your report!

It seems like that NLTK data download was skipped on install for some reason. Could you please try to do it explicitly with `rymtracks --update-languages`?

**Comment by ghost** [comment] 2014-02-12 02:34
The some result :( ...

**Comment by 9seconds** [comment] 2014-02-12 05:29
Could you please paste an output of `rymtracks --update-languages` here then?

**Comment by ghost** [comment] 2014-02-12 05:54
$ rymtracks --update-languages
Traceback (most recent call last):
  File "/usr/bin/rymtracks", line 9, in <module>
    load_entry_point('RYMTracks==0.1.3', 'console_scripts', 'rymtracks')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2029, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib64/python2.7/site-packages/rymtracks/**init**.py", line 51, in <module>
    from .core import execute
  File "/usr/lib64/python2.7/site-packages/rymtracks/core.py", line 8, in <module>
    from .services import Service
  File "/usr/lib64/python2.7/site-packages/rymtracks/services/**init**.py", line 10, in <module>
    from ..capitalization import capitalize
  File "/usr/lib64/python2.7/site-packages/rymtracks/capitalization/**init**.py", line 36, in <module>
    from .py2 import capitalize as specific_capitalize
  File "/usr/lib64/python2.7/site-packages/rymtracks/capitalization/py2.py", line 28, in <module>
    for _language in stopwords.fileids():
  File "/usr/lib64/python2.7/site-packages/nltk/corpus/util.py", line 68, in __getattr__
    self.__load()
  File "/usr/lib64/python2.7/site-packages/nltk/corpus/util.py", line 56, in __load
    except LookupError: raise e
LookupError: 

---

  Resource 'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/dslackw/.rymtracks/nltk'
    - '/home/dslackw/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'

---

**Comment by ghost** [comment] 2014-02-12 05:59
This version work well : http://slackbuilds.org/repository/14.1/network/RYMTracks/?search=RYMTracks

**Comment by 9seconds** [comment] 2014-02-12 07:24
Aha, got it, I see the root cause. Will fix pretty soon. Thanks!

**Comment by ghost** [comment] 2014-02-12 08:49
awaiting !!!

**Comment by 9seconds** [comment] 2014-02-12 09:33
I've submitted the fix, it is already on PyPI and merged into master branch. For some reasons when you install from PyPI custom installation step is not executed. I have to dig into setuptools again to understand the reasons but for now I put warning suggesting to run `rymtracks --update-languages` expliciltly. Proper fix will come with 0.1.4

Thanks for your support!

**Closed as completed** 2014-02-12 09:40 UTC
Labels: bug

**Comment by ghost** [comment] 2014-02-12 09:53
Done Done Done !!!!! Solved !!!
rymtracks -h
RYMTracks scraps given URLs and presents tracklists into copypasteable form
for RateYourMusic.com.

Usage:
    rymtracks <url>...
    rymtracks -f <filename>
    rymtracks -l
    rymtracks --update-languages
    rymtracks (-h | --help)
    rymtracks --version

Options:
    -h --help           Show this screen.
    --version           Show version.
    --update-languages  Installs languages datafiles for proper RYM
                        capitalization
    -f                  Filename with urls.
    -l                  Show parseable network locations.

Thanks!
